---
title: "compbio_proj"
author: "David Lim, Mark He, Mike Lafferty"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: html_document
---
Introduction:
<Mike>


Figures:
<David>






Figure 1C:

```{r}
library(readxl)
library(genefilter)

X <- read_excel("rnaseq_CNS_all.xlsx")

# filter out genes with 0 SD (or 0 variance)
X.SDs <- rowSds(X[,-1])
good = (X.SDs!=0)

X = X[good,]

cor_mat = cor(X[,-1],method="spearman")
library(pheatmap)
pheatmap(cor_mat)
```

Figure 1D:

```{r}
sel_genes = c("Gfap","Aldh1l1","Slc1a3","Aqp4","Tubb3",
              "Stmn2","Snap25","Eno2","Syn1","Pdgfra",
              "Cspg4","Enpp6","Nfasc","Pip","Mog","Mbp",
              "Mobp","Ccl3","Itgam","Tnf","Cldn5","Flt1","Esam")    # Itgam = Cd11b in paper

sel_X <- X[X$gene.symbol %in% sel_genes,]  # subsetting genes and omitting WB1,2,3
sel_X <- sel_X[c(10,1,17,2,22,19,18,6,20,16,5,7,15,14,12,13,3,11,21,4,9,8),]
sel_Xcts <- sel_X[,-1]                       # subset just the counts

sel_means <- rowMeans(sel_Xcts)
sel_sd <- rowSds(sel_Xcts)


num_sd <- matrix(0,nrow=nrow(sel_Xcts),ncol=ncol(sel_Xcts))
for(i in 1:nrow(sel_Xcts)){
  num_sd[i,] <- (as.numeric(sel_Xcts[i,]) - sel_means[i])/sel_sd[i]    # calculate # of SD's away from rowMean
}

rownames(num_sd) <- as.matrix(sel_X[,1])
colnames(num_sd) <- colnames(sel_X[,-1])

pheatmap(num_sd,cluster_cols=F,cluster_rows=F)

##### ISSUES TO RESOLVE: #####
# "Pip" gene has count all = 0.1 --> sd = Inf ??? (row 17)
# Max SDs is 2 in figure. 3 here
# Need to reorder sel_X or num_sd to match the figure
```

Note: "Cd11b" not found. Different name: "Itgam". Also, Pip yielded SD = 0 --> omitted.

FIGURE 3B using Row variances instead of "enrichment":
```{r}
# Using genes with top 40 row variances
std.dev <- rowSds(X[,2:15])
sel.X <- X[which(order(std.dev)<=100),]

hc = hclust(dist(t(sel.X[,2:15])))
plot(hc)
```

```{r}
genes <- sel.X[,1]
sel.X <- sel.X[,2:15]

sel_means <- rowMeans(sel.X)
sel_sd <- rowSds(sel.X)

num_sd <- matrix(0,nrow=nrow(sel.X),ncol=ncol(sel.X))
for(i in 1:nrow(sel.X)){
  num_sd[i,] <- (as.numeric(sel.X[i,]) - sel_means[i])/sel_sd[i]    # calculate # of SD's away from rowMean
}

rownames(num_sd) = as.matrix(genes)
colnames(num_sd) = colnames(sel.X)

dists = dist(num_sd)
hc = hclust(dists)

Y = t(num_sd)[,hc$order]


pheatmap(Y,cluster_rows=F,cluster_cols=F,show_colnames=F)


```







Correlating 2 cell types:
<Mark>


Cibersort:
<Mike>


Conclusions:



